### ISSUE TITLE
I can not find “data” from package

### ISSUE THREAD

**Issue by liuxueyang23** [JayL323/K230_AI_Demo_Development_Process_Analysis#2]
Where is the “data” of using in the face_detector.py? please tell me the source or package
Traceback (most recent call last):
  File "face_detector.py", line 8, in <module>
    from prior_box import PriorBox
  File "/home/shxly/K230/k230_canmv/K230_AI_Demo_Development_Process_Analysis-main/K230_AI_Demo_Development_Process_Analysis-main/onnx_related/onnx_inference/face_detection/prior_box.py", line 4, in <module>
    from data import cfg_mnet
ModuleNotFoundError: No module named 'data'

**Comment by liuxueyang23** [comment]
OK,I just take "data" change to "config" is running! maybe it just a bug in coding.

**Comment by JayL323** [comment]
It was indeed an issue with the code, which I have now resolved. Thank you for the feedback.

**Comment by Green-Taurus** [comment]
How can I contact you, I have a question
